# 通用配置
runmode: debug
addr: :8080
jwt-secret: Rthsiadsao123bjasdioa

# HTTPS 服务器相关配置
tls:
  addr: :8443
  cert: ./_output/cert/server.crt
  key: ./_output/cert/server.key

# GRPC 相关配置
grpc:
  addr: :9090

# MySQL 数据库相关配置
db:
  host: 114.132.232.3
  port: 3307
  username: root
  password: hcybeyond
  database: prompting
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s
  log-level: 4 # Gorm log level,1: silent 2:error 3:warn 4:info

# Redis 数据库相关配置
redis:
  host: 114.132.232.3
  port: 6480
  init: false
  cert: hcybeyond


# 日志配置
log:
  disable-caller: false # 是否开启caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-stacktrace: false # 是否禁止在 panic 及以上级别打印堆栈信息
  level: debug # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  format: console # 指定日志显示格式，可选值：console, json
  output-paths: [/tmp/prompting.log, stdout]  # 指定日志输出位置，多个输出，用 `逗号 + 空格` 分开。stdout：标准输出，stderr：标准错误输出，/tmp/miniblog.log：文件输出